---
title: "IntroducciónR"
author: "Sarai Gaibor"
date: '2022-02-26'
output:
  html_document:
    mathjax: "http://example.com/MathJax.js"
    self_contained: true
    fig_height: 6
    fig_width: 8
    theme: journal
    highlight: zenburn
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r 1 }
# Tarea bioinformática

#Crear un identificador de nombre "ciudad" y asigne como valos el nombre de alguna ciudad.

ciudad <- "Quito"
print (ciudad) 
ciudad

#Crear un identificador de nombre "paises_andes" y asigne como valor los nombres de los paísses por donde cruza la cordillera de los Andes.

paises_andes <-c("Venezuela","Perú","Ecuador","Colombia","Chile","Bolivia","Argentina")
print (paises_andes)

#Crear un dataframe con 12 eventos (files) y 5 variables (columnas), cada columna debe tener diferentes tipos de datos.

poblacion_paises <- data.frame(identificador = seq(1:12),
              sur_norte = as.factor(c(rep(0, 7),1,1,1,1,1)),
              paises = c("Argentina","Bolivia","Brasil","Chile","Colombia",
              "Ecuador","Paraguay","Afganistan","Alemania","Andorra","Argelia"
              ,"Bahamas"),
              poblacion = c(45.38, 11.67, 212.6, 19.12, 50.88, 17.64, 7.133, 38.93, 83.24,77.265, 43.85, 393.248)) 
print (poblacion_paises)              

#Cargue el dataset "DNase" e identifique su estructura. Extraiga (subset) 
# los datos que cumplan con las condiciones de: 
# 1. "conc" (concentracion) entre 0.1 y 0.2
# 2. "Run" diferente a 2, "conc" mayor a 0.2 y "density" menor o igual a 1.0
```

```{r 2}

setwd("C:/Users/User/Documents")
database <- data("DNase")
class(DNase)
library(dplyr)
first_filter <- filter(DNase, conc < 0.2 & conc > 0.1)
second_filter <- filter(DNase, Run !=2 & conc > 0.2 & density <= 1)
print(first_filter)
print(second_filter)
```
```



